<?xml version="1.0"?>
<robot xmlns:xacro="https://www.ros.org/wiki/xacro">

    <!-- Arm properties -->
    <xacro:property name="box_length" value="0.1" />
    <xacro:property name="box_width" value="0.1" />
    <xacro:property name="box_height" value="0.02" />
    <xacro:property name="box_mass" value="0.5"/>
    <xacro:property name="forearm_radius" value="0.02"/>
    <xacro:property name="forearm_length" value="0.3"/>
    <xacro:property name="forearm_mass" value="0.3"/>
    <xacro:property name="hand_radius" value="0.02"/>
    <xacro:property name="hand_length" value="0.3"/>
    <xacro:property name="hand_mass" value="0.3"/>

    <!-- Box link (base) -->
    <link name="arm_base_link">
        <visual>
            <origin xyz="0.0 0.0 ${box_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${box_length} ${box_width} ${box_height}"/>
            </geometry>
            <material name="orange" />
        </visual>

        <collision>
            <origin xyz="0.0 0.0 ${box_height/2}" rpy="0 0 0" />
            <geometry>
                <box size="${box_length} ${box_width} ${box_height}" />
            </geometry>
        </collision>

        <xacro:box_inertia m ="${box_mass}" x="${box_length}" y="${box_width}" z="${box_height}"
                           o_xyz="0 0 ${box_height/2}" o_rpy="0 0 0"/>
    </link>

    <!-- Forearm link -->
    <link name="forearm_link">
        <visual>
            <origin xyz="0.0 0.0 ${forearm_length/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}"/>
            </geometry>
            <material name="yellow" />
        </visual>

        <collision>
            <origin xyz="0.0 0.0 ${forearm_length/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}"/>
            </geometry>
        </collision>

        <xacro:cylinder_inertia m="${forearm_mass}" r="${forearm_radius}" h="${forearm_length}"
                                o_xyz="0 0 ${forearm_length/2}" o_rpy="0 0 0"/>
    </link>

    <!-- Base forearm joint -->
    <joint name="base_forearm_joint" type="revolute">
        <parent link="arm_base_link"/>
        <child link="forearm_link"/>
        <origin xyz="0.0 0.0 ${box_height}" rpy="0.0 0.0 0.0"/>    
        <limit lower="0.0" upper="${pi/2}" effort="100" velocity="100"/>
        <dynamics friction="0.3" damping="0.3"/>
    </joint>

    <!-- Hand link -->
    <link name="hand_link">
        <visual>
            <origin xyz="0.0 0.0 ${hand_length/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}"/>
            </geometry>
            <material name="orange" />
        </visual>

        <collision>
            <origin xyz="0.0 0.0 ${hand_length/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}"/>
            </geometry>
        </collision>

        <xacro:cylinder_inertia m="${hand_mass}" r="${hand_radius}" h="${hand_length}"
                                o_xyz="0 0 ${hand_length/2}" o_rpy="0 0 0"/>
    </link>

    <!-- Forearm hand joint -->
    <joint name="forearm_hand_joint" type="revolute">
        <parent link="forearm_link"/>
        <child link="hand_link"/>
        <origin xyz="0.0 0.0 ${forearm_length}" rpy="0.0 0.0 0.0"/>
        <limit lower="0" upper="${pi/2}" effort="100" velocity="100"/>
        <dynamics friction="0.3" damping="0.3"/>
    </joint>
</robot>