<?xml version="1.0"?>
<robot xmlns:xacro="https://www.ros.org/wiki/xacro">
    <!-- Xacro Variables-->
    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />


    <!-- base_footprint-->
    <link name="footprint_link" />

    <!-- Base link-->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" /> 
            </geometry>
            <material name="blue" />
        </visual>

        <collision>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" /> 
            </geometry>
        </collision>

        <xacro:box_inertia m="5.0" 
                           x="${base_length}" y="${base_width}" z="${base_height}" 
                           o_xyz="0 0 ${base_height/2}" o_rpy="0 0 0" />
    </link>
    
    <!-- footprint base joint-->
    <joint name="footprint_base_joint" type="fixed">
        <parent link="footprint_link"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 ${wheel_radius}" rpy="0.0 0.0 0.0"/>
    </joint>

    <!-- wheel macro, predefined objects, just like in kivy-->
    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link"> 
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2.0} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <material name="grey" />
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2.0} 0.0 0.0"/>
                <geometry>
                    <sphere radius="${wheel_radius}"/>
                </geometry>
            </collision>

            <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" h="${wheel_length}"
                                    o_xyz="0 0 0" o_rpy="${pi/2} 0 0"/>
        </link>
    </xacro:macro>

    <!-- Right wheel link-->
    <xacro:wheel_link prefix="right" />

    <!-- Base right_wheel joint -->
    <joint name="base_rightwheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="${-base_length/4.0} ${-base_width/2 - wheel_length/2} 0.0" rpy="0.0 0.0 0.0"/>
        <axis xyz="0.0 1.0 0.0"/>
    </joint>

    <!-- Left wheel link-->
    <xacro:wheel_link prefix="left" />

    <!-- Base left joint -->
    <joint name="base_leftwheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="${-base_length/4.0} ${base_width/2 + wheel_length/2} 0.0" rpy="0.0 0.0 0.0"/>
        <axis xyz="0.0 1.0 0.0"/>
    </joint>

    <!-- Caster wheel link-->
    <link name="caster_wheel_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${wheel_radius/2}"/>
            </geometry>
            <material name="grey" />
        </visual>    

        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${wheel_radius/2}"/>
            </geometry>  
        </collision>

        <xacro:sphere_inertia m="0.5" r="${wheel_radius/2}"
                               o_xyz="0 0 0" o_rpy="0 0 0"/>
    </link>

    <!-- Casterwheel base joint-->
    <joint name="caster_wheel_base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_link"/>
        <origin xyz="${base_length/3.0} 0.0 ${-wheel_radius/2}" rpy="0.0 0.0 0.0"/>
    </joint>
</robot>