<?xml version="1.0"?>
<robot xmlns:xacro="https://www.ros.org/wiki/xacro">

    <gazebo reference="caster_wheel_link">
        <mu1 value="0.1" />
        <mu2 value="0.1" />
    </gazebo>

    <gazebo>
        <plugin filename="gz-sim-diff-drive-system"
                name="gz::sim::systems::DiffDrive">
            <left_joint>base_leftwheel_joint</left_joint>
            <right_joint>base_rightwheel_joint</right_joint>
            <wheel_separation>${base_width + wheel_length}</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>
            <frame_id>odom</frame_id>
            <child_frame_id>footprint_link</child_frame_id>
        </plugin>
    </gazebo>

    <gazebo>
        <plugin filename="gz-sim-joint-state-publisher-system"
                name="gz::sim::systems::JointStatePublisher">
            <joint_name>base_leftwheel_joint</joint_name>
            <joint_name>base_rightwheel_joint</joint_name>
        </plugin>
    </gazebo>

</robot>